# Generated by Django 5.1.3 on 2024-11-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_container_country_currency_city_terminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
    ]
