# Generated by Django 5.1.3 on 2024-11-14 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_department_options_alter_position_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short Name')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Delivery Type',
                'verbose_name_plural': 'Delivery Types',
            },
        ),
        migrations.CreateModel(
            name='Incoterms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=3, unique=True, verbose_name='Abbreviation')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Incoterms',
                'verbose_name_plural': 'Incoterms',
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_uk', models.CharField(max_length=100, verbose_name='Name (Ukrainian)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
            },
        ),
        migrations.CreateModel(
            name='DangerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=2, verbose_name='Class Number')),
                ('sub_class', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sub Class')),
                ('un_code', models.CharField(max_length=4, verbose_name='UN Code')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Danger Class',
                'verbose_name_plural': 'Danger Classes',
                'unique_together': {('class_number', 'sub_class', 'un_code')},
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Name (Ukrainian)')),
                ('cargo_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Cargo code must be between 4 and 10 digits', regex='^\\d{4,10}$')], verbose_name='Cargo Code')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Is Dangerous')),
                ('description', models.TextField(verbose_name='Description')),
                ('danger_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.dangerclass', verbose_name='Danger Class')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargoes',
            },
        ),
    ]
