# Generated by Django 5.1.3 on 2024-11-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_deliverytype_incoterms_packagingtype_dangerclass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_employees_list', 'Can view employees list'), ('view_employee_details', 'Can view employee details'), ('edit_employee_info', 'Can edit employee information')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Additional Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Additional Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='living_address',
            field=models.TextField(blank=True, null=True, verbose_name='Living Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_address',
            field=models.TextField(blank=True, null=True, verbose_name='Registration Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termination Date'),
        ),
    ]
