# Generated by Django 5.1.3 on 2024-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='incoterms',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
